### ISSUE TITLE
Handling of data graph in Store

### ISSUE THREAD

**Issue by beauby** [confetti/yayson#10]
From what I understand, the Store works in the following way:
- when new data is synced, all records are stored (or updated if already present) in the `records` property;
- the data graph is then recomputed on the fly for the connected component of the top level records of the data payload (`body.data`).

While this works, I see two drawbacks to this approach:
- the data graph is recomputed more than necessary (what is the rationale behind it not being stored directly?);
- suppose I sync some `Article` records (with `Comments` not included), and sync them. Then when I fetch my `Comments`, my `article` model is not updated (i.e. it still does not have comments attached).

I would love to work on a PR for this but would like your input to make sure I haven't missed anything obvious.

**Comment by jede** [comment]
Interesting, I'd love for the `Store` to get faster!

Not quite sure I'm following. What happens is that the `Store` saves the data objects as `Record`s. The `Record` is just a representation of the data it got from the JSON, so no connections are made there, just as raw data as possible. Then when someone asks for something in the store, we construct a model for every `Record` that is included in the query (with connections). When the query is complete, we throw away the models and connections that where created. This can sometimes be a waste, but since caching often leads to lots of bugs I'd been hesitant to add it. 

The `Article` situation you mention should work fine, do you have an issue like that now?

**Comment by jede** [comment]
Closing this, please reopen if its still an issue.
